In [36]:
import numpy as np
import time
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
import math

[Activation functions](https://github.com/Kulbear/deep-learning-nano-foundation/wiki/ReLU-and-Softmax-Activation-Functions)

In [37]:
#Sigmoid
def sigmoid_f(x):
    return 1 / (1 + np.exp(-x))
    
def sigmoid_df(x):  
    sig=sigmoid_f(x)
    return sig*(1-sig)
    
#ReLU
def ReLU_f_over(x):
    return x*(x>0)

def ReLU_f(x): 
    return np.where(x > 0, x, 0)


def ReLU_df(x):
    return np.where(x <= 0, 0, 1)

#Softmax
def softmax_my(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def softmax_df(x):  
    soft=softmax_f(x)
    return soft*(1-soft)

def softmax_f(x):  # работает
    temp = math.e**x
    div = temp.sum(axis=1)
    return np.transpose((np.divide(np.transpose(temp), np.transpose(div))))

    
    

In [38]:
import os
from sklearn.datasets import fetch_mldata

# Fetch MNIST dataset and create a local copy.
if os.path.exists('mnist.npz'):
    with np.load('mnist.npz', 'r') as data:
        X = data['X']
        y = data['y']
else:
    mnist = fetch_mldata("mnist-original")
    X, y = mnist.data / 255.0, mnist.target
    np.savez('mnist.npz', X=X, y=y)

In [39]:
print(np.shape(y.reshape(-1,1)))

(70000, 1)


In [40]:
from sklearn.preprocessing import OneHotEncoder
# Convert labels to One Hot Encoded
num_digits = 10
encoder = OneHotEncoder(categorical_features =[0]) 
y_one_hot = encoder.fit_transform(y.reshape(-1, 1)).toarray()
print(y_one_hot[50000,:])

# def to_one_hot(y): 
#     one_hot_y = np.zeros((len(y), num_digits))
#     for i in range(len(y)):
#         one_hot_y[i, int(one_hot_y[i])] = 1
#     return one_hot_y

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [41]:
from sklearn.utils import shuffle
X,y=shuffle(X,y)
#Split into test , train based on Kaggle
X_train=X[:60000,:]
y_train=y_one_hot[:60000,:]

X_test=X[60000:,:]
y_test=y_one_hot[60000:,:]
print(np.shape(X_train))
print(np.shape(y_test))

(60000, 784)
(10000, 10)


In [42]:
def he_initialization(size_prev, size_next):  # HE initialization for matrix weights
    return np.random.randn(size_prev, size_next) * np.sqrt(2.0/size_prev)

In [140]:
#Expects weights and bias to be a matrix and a vector, activation_function to be a value= 1,2 or 3
#Use when need to store z, h at each layer (for deltas)
def layer_predict(inputs, weights, bias, activation_function):
    #main sum counting z
    #bias as vector adds to each row of weight matrix
    #example: weights (300, 784), inputs (10000,784), bias (300,) then out (10000, 300)
    out = np.add(np.dot(weights, inputs.T).T, bias)
    # return z and h=f(z), f activation as parameter
    if activation_function == 1:
        return out, sigmoid_f(out)
    if activation_function == 2:
        return out, ReLU_f(out)
    if activation_function == 3:
        return out, softmax_f(out)
#Expects z to be a matrix , activation_function to be a value= 1,2 or 3
#Use when counting delta back propagate using derivatives
def layer_back_propagate_derivatives(z, activation_function):
    if activation_function == 1:
        return sigmoid_df(z)
    if activation_function == 2:
        return ReLU_df(z)
    if activation_function == 3:
        return softmax_df(z)
    
#Expects weights and bias to be a list of matrixes and a list of vectors 
#Use when given input data gets output without storing hidden layers values
def neural_predict(x_data, weights_in, biases_in, neural_architecture):  
    #for each layer in neural architecture (same dim as weights)
    activation_functions=neural_architecture[:,2]
    h=[]
    
    for layer in range(0, len(neural_architecture)):  
    
        #initial layer then take x_data as input
        if layer == 0:
            z_temp, h_temp = layer_predict(x_data, weights_in[layer],biases_in[layer], activation_functions[layer])
            h = h_temp
        else:
            #take h-previous layer output as input
            z_temp, h_temp = layer_predict(h, weights_in[layer],biases_in[layer], activation_functions[layer])
            h = h_temp

    return h
    
def convert_to_binary(vector):
    row_maxes = vector.max(axis=1).reshape(-1, 1)
    vector[:] = np.where(vector == row_maxes, 1, 0)
    return vector

def root_mean_square_error(y_predict,y_actual):
    y_predict=convert_to_binary(y_predict)
    mse=np.sum(np.power(y_actual-y_predict,2))/len(y_predict)
    return np.sqrt(mse)


In [141]:
def calculate_by_argmax(y_data, prediction):  # argmax for MSE gradient
    argmaxes = np.argmax(prediction, axis=1)
    temp = np.choose(argmaxes, y_data.T) - np.ones(len(prediction))
    temp = temp * temp
    return np.sum(temp) / len(y_data)


def calculate_prediction(x_data, y_data, w_matrices, biases, activation_functions):  # prediction for accuracy
    h = []
    for i in range(0, len(w_matrices)):  # forward one batch

        if i == 0:
            z_temp, h_temp =layer_predict(x_data, w_matrices[i],
                                           biases[i], activation_functions[i])
            h = h_temp
        else:
            z_temp, h_temp = layer_predict(h, w_matrices[i],
                                           biases[i], activation_functions[i])
            h = h_temp

    return calculate_by_argmax(y_data, h)

In [153]:
def one_epoch_mini_batch_gradient_step(X_train,y_train,w_weights,b_biases,neural_architecture,activation_functions,learning_rate,num_epoches,batch_size):
    #A list of outputs of each layer
    h =[]
    #A list of weightned sum for each layer
    z=[]
    weights = w_weights.copy()
    biases = b_biases.copy()
    X_train,y_train=shuffle(X_train,y_train)
    n_minibatches = X_train.shape[0] // batch_size #1875
    i = 0
    for i in range(n_minibatches):
        #A list of outputs of each layer
        h =[]
        #A list of weightned sum for each layer
        z=[]
        deltas=[]
        X_mini=X_train[i * batch_size:(i + 1)*batch_size, :] #(32,784)
        y_mini=y_train[i * batch_size:(i + 1)*batch_size,:] #(32,10)
        #print(np.shape(X_mini))   
        #print(np.shape(y_mini)) 
        N=X_mini.shape[0] #32...
        #PARAMETERS
            
        #Forward propagation
        layers_amount=len(neural_architecture)
        #weights=w_weights.copy()
        #biases=b_biases.copy()
        for layer in range(0, layers_amount):
            #For initial layer take X as input
            if layer==0:
                inputs=X_mini
                #z_temp, h_temp= layer_predict(X_mini, weights[layer], biases[layer], activation_functions[layer])
            #For any other layer take previous layer output as input
            else:
                inputs=h[layer-1]
                #z_temp, h_temp= layer_predict(h[layer-1], weights[layer], biases[layer], activation_functions[layer])
            #Store as lists
            z_temp, h_temp= layer_predict(inputs, weights[layer], biases[layer], activation_functions[layer])
            z.append(z_temp) #0=(32,300) 1=(32,100) 2=(32,10)
            h.append(h_temp)
#             print("Layer Outputs")
#             print(h[layer])
#             print(layer)
#             print(z[layer])
                
        #y_predict=neural_predict(X_mini,weights,biases,neural_architecture) same as h[layers_amount - 1]
        # z,y_predict=layer_predict(h[layer_amount-1],weights[layer_amount-1],biases[layer_amount-1],
        #activation_functions[layer_amount-1])
        #error=y_mini-y_predict 
            
        #DELTA INITIAL AND HIDDEN HERE
            
        #Initialize empty list size as amount of layers in network
        deltas= np.empty(layers_amount, dtype=object)
        #Count last delta based on (1)
        #(32,10)
        delta_last = np.multiply((h[layers_amount - 1] - y_mini),layer_back_propagate_derivatives(z[layers_amount - 1], activation_functions[layers_amount - 1])) 
        #Store last delta in list
#         print("Delta Last")
#         print(delta_last)
        deltas[layers_amount-1]=delta_last # matrix size (dataset_size,amount_of_neurons_on_this_layer) transpose weights
        #Back propagating with step=1 , stop=-1 (need count on layer=0) 
        for layer in range(layers_amount-2,-1,-1):
            #Counting delta on hidden layers based on (2)
            deltas[layer]=np.multiply((deltas[layer+1]).dot(weights[layer+1]),layer_back_propagate_derivatives(z[layer], activation_functions[layer]))    
#         for layer in range(0, layers_amount):
#             print("Deltas")
#             print(i)
#             print(deltas[layer])
        #PARAMETERS UPDATES USING DELTAS
        for layer in range(0, layers_amount):
            #For initial layer take X as input
            if layer==0:
                inputs=X_mini
            #For any other layer take previous layer output as input
            else:
                inputs=h[layer-1]
            #update weights
            lN=learning_rate/N
            biases[layer]=biases[layer]-lN*np.sum(deltas[layer],axis=0)
            weights[layer]=weights[layer]-lN*((deltas[layer].T).dot(inputs))
#             print("Learned")
#             print(layer)
#             print(biases[layer])
#             print(layer)
#             print("Weights")
#             print(weights[layer] )
    return weights,biases

In [160]:
def mini_batch_gradient_descent(X_train,y_train,neural_architecture,learning_rate,num_epoches,batch_size):
    #A list of matrixes size of (new_layer_neurons_amount,prev_layer_neurons_amount)
    w_weights=[]
    #A list of vectors size of (new_layer_neurons_amount,1)
    b_biases=[]
    accuracy=[]
    accuracy2=[]
   
    for layer in range(0, len(neural_architecture)):
        #For first time forward propagation random initialization
        #w_weights.append(np.full((neural_architecture[layer][1], neural_architecture[layer][0]), 0.99))
        w_weights.append(he_initialization(neural_architecture[layer,1],neural_architecture[layer,0]))#(300, 784) (100, 300) (10, 100)
        b_biases.append(np.zeros(neural_architecture[layer][1])) #(300,) (100,) (10,)
#         print("Initial weights random")
#         print(w_weights[layer])
#         print(b_biases[layer])
    #Just to store as list    
    activation_functions=neural_architecture[:,2]
    it=0
    for it in range(num_epoches):
        #print(weights[0][::100,::50])
        #print(biases[0][::100])
        w1=w_weights
        b1=b_biases
        w_weights,b_biases=one_epoch_mini_batch_gradient_step(X_train,y_train,w_weights,b_biases,neural_architecture,activation_functions,learning_rate,num_epoches,batch_size)
#         for layer in range(0, len(neural_architecture)):
#             print("Epoches changed from initial?")
#             print(w_weights[layer])
#             print(b_biases[layer])
        y_predict=neural_predict(X_test,w_weights,b_biases,neural_architecture)
#         print(y_predict)
#         convert_to_binary(y_predict)
         
        print(it)
        #accuracy.append(calculate_prediction(X_test, y_test, w_weights, b_biases, activation_functions))
        accuracy2.append(calculate_by_argmax(y_test,y_predict))
        convert_to_binary(y_predict)
        accuracy.append(accuracy_score(y_test,y_predict)*100)
        print(accuracy)
        print(accuracy2)
    return w_weights,b_biases

In [161]:
rmse=[]
omega=[]
omega0=[]
rmse_train=[]

#Already initialized
#X_test (10000, 784)
#y_test (10000, 10)

#X_train (60000, 784)
#y_train (60000, 10)
      
start = time.time()
    
neural_architecture= np.array([[784, 300, 1, 0],[300, 10, 3, 0]])

weights_item,bias_item=mini_batch_gradient_descent(X_train,y_train,neural_architecture,learning_rate = 0.01,num_epoches=30,batch_size=32)
stop = time.time()
duration = stop-start
print(duration)
    
        
#NEED TO PLOT ACCURACY

0
[9.99]
[0.9001]
1
[9.99, 9.92]
[0.9001, 0.9008]
2
[9.99, 9.92, 10.15]
[0.9001, 0.9008, 0.8985]
3
[9.99, 9.92, 10.15, 9.9]
[0.9001, 0.9008, 0.8985, 0.901]
4
[9.99, 9.92, 10.15, 9.9, 10.2]
[0.9001, 0.9008, 0.8985, 0.901, 0.898]
5
[9.99, 9.92, 10.15, 9.9, 10.2, 10.31]
[0.9001, 0.9008, 0.8985, 0.901, 0.898, 0.8969]
6
[9.99, 9.92, 10.15, 9.9, 10.2, 10.31, 10.33]
[0.9001, 0.9008, 0.8985, 0.901, 0.898, 0.8969, 0.8967]
7
[9.99, 9.92, 10.15, 9.9, 10.2, 10.31, 10.33, 10.42]
[0.9001, 0.9008, 0.8985, 0.901, 0.898, 0.8969, 0.8967, 0.8958]
8
[9.99, 9.92, 10.15, 9.9, 10.2, 10.31, 10.33, 10.42, 10.32]
[0.9001, 0.9008, 0.8985, 0.901, 0.898, 0.8969, 0.8967, 0.8958, 0.8968]
9
[9.99, 9.92, 10.15, 9.9, 10.2, 10.31, 10.33, 10.42, 10.32, 10.11]
[0.9001, 0.9008, 0.8985, 0.901, 0.898, 0.8969, 0.8967, 0.8958, 0.8968, 0.8989]


KeyboardInterrupt: 

In [ ]:
from matplotlib import pyplot as plt

def mse_plot(rmse):  
    plt.figure(figsize=(7, 7))
    plt.plot(rmse, label="MSE train")
    plt.legend()
    plt.show()
    
mse_plot(rmse)    

In [ ]:
deltas= np.empty(5, dtype=object)
print(deltas)
omega=np.full((3, 2), 0.5)
deltas[2]=omega
print(deltas)

In [ ]:
X_test,y_test=shuffle(X_test,y_test)
inputs=X_test[:100,:]  
weights=[]
neural_architecture= np.array([[784, 300, 1, 0],[300, 100, 1, 0],[100, 10, 3, 0]])
activation_functions=neural_architecture[:,2]
biases=[]
#A list of outputs of each layer
h =[]
#A list of weightned sum for each layer
z=[]
deltas= np.zeros(len(neural_architecture), dtype=object)    
for layer in range(0, len(neural_architecture)):
    #For first time forward propagation random initialization
    #weights.append(he_initialization(neural_architecture[layer,1],neural_architecture[layer,0]))
    #weights.append(np.zeros(neural_architecture[layer][1],neural_architecture[layer][0]))
    weights.append(np.full((neural_architecture[layer][1], neural_architecture[layer][0]), 0))
    biases.append(np.zeros(neural_architecture[layer][1]))
    #Just to store as list

    
out = np.add(np.dot(weights[0], inputs.T).T, biases[0])
#print(np.shape(weights))
#print( len(neural_architecture))
#print(len(weights))

z,y_predict=layer_predict(inputs,weights[0],biases[0],1)
z,y2=layer_predict(y_predict,weights[1],biases[1],1)
z,y3=layer_predict(y2,weights[2],biases[2],3)

y3_2=neural_predict(inputs,weights, biases, neural_architecture)
#print(np.shape(y3_2))
#convert_to_binary(y_predict)
#print(softmax_f(out3))
layers_amount=len(neural_architecture)
        #weights=w_weights.copy()
        #biases=b_biases.copy()
        #A list of outputs of each layer
h =[]
#A list of weightned sum for each layer
z=[]
for layer in range(0, layers_amount):
            #For initial layer take X as input
    if layer==0:
        inputs1=X_test[:100,:]
                #z_temp, h_temp= layer_predict(X_mini, weights[layer], biases[layer], activation_functions[layer])
            #For any other layer take previous layer output as input
    else:
        inputs1=h[layer-1]
                #z_temp, h_temp= layer_predict(h[layer-1], weights[layer], biases[layer], activation_functions[layer])
            #Store as lists
    z_temp, h_temp= layer_predict(inputs1, weights[layer], biases[layer], activation_functions[layer])
    z.append(z_temp) #0=(32,300) 1=(32,100) 2=(32,10)
    h.append(h_temp)
#print(np.shape(h[layers_amount - 1] - y_test[:100,:]))
#print(np.shape(layer_back_propagate_derivatives(z[layers_amount - 1], activation_functions[layers_amount - 1])))
delta_last = np.multiply((h[layers_amount - 1] - y_test[:100,:]),layer_back_propagate_derivatives(z[layers_amount - 1], activation_functions[layers_amount - 1]))
#print( h[layers_amount - 1] - y_test[:100,:])
#print(delta_last)
deltas[layers_amount-1]=delta_last

for layer in range(layers_amount-2,-1,-1):
    #Counting delta on hidden layers based on (2)
    #print(np.shape(layer_back_propagate_derivatives(z[layer], activation_functions[layer])))
    deltas[layer]=np.multiply((deltas[layer+1]).dot(weights[layer+1]),layer_back_propagate_derivatives(z[layer], activation_functions[layer])) 

print(np.shape(deltas[2]))

for layer in range(0, layers_amount):
    #For initial layer take X as input
    if layer==0:
        inputs2=X_test[:100,:]
    #For any other layer take previous layer output as input
    else:
        inputs2=h[layer-1]
                #update weights
    N=100
    #print(np.shape(weights[layer]))
    biases[layer]=biases[layer]-0.001*np.sum(deltas[layer],axis=0)/N
    weights[layer]=weights[layer]-0.001*((deltas[layer].T).dot(inputs2))/N
    #print(weights[layer])
print(deltas[2].T)
print(h[1])
print((deltas[2].T).dot(h[1]))
print(weights[2])


In [ ]:

layer=0
for layer in range(len(neural_architecture)):
    #print(np.shape(weights[layer]))
    print(len(neural_architecture))

In [ ]:
xs = np.array([[0.5, 0.5, 0.5, 0.5,0.5,0.5, 0.5, 0.5, 0.5,0.5],
             [0.5, 0.5, 0.5, 0.5,0.5,0.5, 0.5, 0.5, 0.5,0.5],
             [0.5, 0.5, 0.5, 0.5,0.5,0.5, 0.5, 0.5, 0.5,0.5]])
print(softmax_f(xs)) 

In [ ]:
print(X_train[::2000,::50])

In [ ]:
#print(-5.62601022e-051 )
numbers = [1.74408899e-012, 2.37943956e-004, 2.63039636e-006, 2.55056039e-010,
  3.21408160e-051, 9.99759377e-001, 2.54537571e-008, 2.25822913e-008,
  2.00556809e-037, 2.19572601e-128]

for number in numbers:
    print(f'{number:9.51f}')

In [119]:
learning_rate = 0.001
num_epoches = 1
batch_size = 20

def data_generation(size_1, size_2):
    return np.random.rand(size_1, size_2)

gen_data = data_generation(20, 8)
#y_data = data_generation(20, 2)
y_data=np.full((20,2), 1)
#y_data=np.random.randint(0,2,(20,2))
#gen_data=np.full((20,8), 0.5)
list_architecture = np.array([
        [8, 6, 1],
        [6, 4, 2],
        [4, 2, 3]
    ])
print(gen_data)
print(y_data)


[[0.63545512 0.1079984  0.71183677 0.43545901 0.22038128 0.20563826
  0.95610961 0.81038951]
 [0.29182697 0.81015226 0.77189123 0.88343589 0.59548193 0.37270566
  0.99845906 0.67199526]
 [0.76884845 0.20407328 0.89136258 0.06528111 0.94945119 0.29110495
  0.23255144 0.846693  ]
 [0.60169768 0.85712308 0.8410921  0.18386703 0.51960696 0.17866907
  0.52596265 0.66310269]
 [0.75487943 0.97319764 0.98954629 0.63427001 0.35049353 0.13045448
  0.9823206  0.11418535]
 [0.07500125 0.5360988  0.18971054 0.31182801 0.97647321 0.09865844
  0.25085084 0.8066556 ]
 [0.18699095 0.36253489 0.47442783 0.35574654 0.96519    0.8248316
  0.05706355 0.79536978]
 [0.02832364 0.99930732 0.48939381 0.32887041 0.05291127 0.61949636
  0.21031375 0.46299726]
 [0.74089384 0.93413143 0.41533738 0.70721778 0.15872329 0.98062316
  0.09897326 0.90376138]
 [0.17718098 0.78990528 0.98451477 0.45298997 0.94253666 0.57075748
  0.87283106 0.63864766]
 [0.31668118 0.8975891  0.02104956 0.21191122 0.23980325 0.50840185
  0

In [123]:

weights_item,bias_item=mini_batch_gradient_descent(gen_data,y_data,list_architecture,learning_rate = 0.001,num_epoches=11,batch_size=20)

y_predict=neural_predict(gen_data,weights_item,bias_item,list_architecture)
print("Predict")
print(y_predict)

Initial weights random
[[0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99 0.99 0.99]]
[0. 0. 0. 0. 0. 0.]
Initial weights random
[[0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99 0.99 0.99]]
[0. 0. 0. 0.]
Initial weights random
[[0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99]]
[0. 0.]
Layer Outputs
[[0.99539075 0.99539075 0.99539075 0.99539075 0.99539075 0.99539075]
 [0.99523646 0.99523646 0.99523646 0.99523646 0.99523646 0.99523646]
 [0.99253669 0.99253669 0.99253669 0.99253669 0.99253669 0.99253669]
 [0.99250338 0.99250338 0.99250338 0.99250338 0.99250338 0.99250338]
 [0.99185791 0.99185791 0.99185791 0.99185791 0.99185791 0.99185791]
 [0.99182772 0.99182772 0.99182772 0.99182772 0.99182772 0.99182772]
 [0.98196318 0.9819631

[[5.90711389 5.90711389 5.90711389 5.90711389]
 [5.72183838 5.72183838 5.72183838 5.72183838]
 [5.90352821 5.90352821 5.90352821 5.90352821]
 [5.84934109 5.84934109 5.84934109 5.84934109]
 [5.89968669 5.89968669 5.89968669 5.89968669]
 [5.87445678 5.87445678 5.87445678 5.87445678]
 [5.84467209 5.84467209 5.84467209 5.84467209]
 [5.72728631 5.72728631 5.72728631 5.72728631]
 [5.70979149 5.70979149 5.70979149 5.70979149]
 [5.90756679 5.90756679 5.90756679 5.90756679]
 [5.92454265 5.92454265 5.92454265 5.92454265]
 [5.84034792 5.84034792 5.84034792 5.84034792]
 [5.490044   5.490044   5.490044   5.490044  ]
 [5.83954899 5.83954899 5.83954899 5.83954899]
 [5.90052089 5.90052089 5.90052089 5.90052089]
 [5.92362478 5.92362478 5.92362478 5.92362478]
 [5.84305845 5.84305845 5.84305845 5.84305845]
 [5.90334949 5.90334949 5.90334949 5.90334949]
 [5.90736851 5.90736851 5.90736851 5.90736851]
 [5.86467385 5.86467385 5.86467385 5.86467385]]
Layer Outputs
[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 

In [118]:
print(0.89561055*0.99 )
print(softmax_my(np.array([23.29357914, 23.29357914] )))

0.8866544445
[0.5 0.5]


In [165]:
X_test,y_test=shuffle(X_test,y_test)
inputs=X_test[:100,:]  
weights=[]
neural_architecture= np.array([[784, 300, 1, 0],[300, 100, 1, 0],[100, 10, 3, 0]])
activation_functions=neural_architecture[:,2]
biases=[]
#A list of outputs of each layer
h =[]
#A list of weightned sum for each layer
z=[]
deltas= np.zeros(len(neural_architecture), dtype=object)    
for layer in range(0, len(neural_architecture)):
    #For first time forward propagation random initialization
    #weights.append(he_initialization(neural_architecture[layer,1],neural_architecture[layer,0]))
    #weights.append(np.zeros(neural_architecture[layer][1],neural_architecture[layer][0]))
    #weights.append(np.full((neural_architecture[layer][1], neural_architecture[layer][0]), 0))
    weights.append(he_initialization(neural_architecture[layer,1],neural_architecture[layer,0]))
    biases.append(np.zeros(neural_architecture[layer][1]))
    #Just to store as list
print(calculate_prediction(X_test, y_test, weights, biases, activation_functions))

0.8965
